defaults:
  - _self_

augmentations:
  gaussian_noise:
    enabled: false
    sigma: 0.02      
  time_warp:
    enabled: false
    warp_ratio: 0.15
    max_seg: 0.5    
  frequency_shift:
    enabled: false
    fs: 250       
    shift_hz: 1.0  
  mixup:
    enabled: false
    alpha: 0.2     
