
source: "fif"
name: "Recorded_Subject"
home: './data/target/subj_1'
dataset: 'target'

sfreq: 250
n_channels: 8
eeg_channels: ['Fz','C3','Cz','C4','PO7','Oz','PO8','Pz']
eog_channels: []

event_markers:
  left_hand: 0
  right_hand: 1
  rest: 2
  "0": "left_hand"
  "1": "right_hand"
  "2": "rest"
unify_annotations: true

preprocessing:
  concatenate_recordings: true 
  split_days: true           
  
  remove_eog_artifacts: false
  show_ica_plots: false
  save_ica_plots: true
  ica_plots_dir: "./ica_plots"

  raw_preprocessors: 
    notch_filter:
      kwargs:
        freq: 50.0
    bandpass_filter:
      kwargs:
        low: 8
        high: 30
        method: 'iir'
    ica:
      kwargs:
        n_components: 8
        method: 'fastica'
        random_state: 42

  epoching:
    kwargs:
      tmin: -1.0                   
      tmax:  2.0                  
      crop_window_length: 3.0     
      crop_step_size:    0.5      
      baseline:         null

  exponential_moving_standardization:
    kwargs:
      smoothing_factor: 0.1
      eps:              1e-5


  output_file: "./dump/preprocessed_target_data.pkl"

  data_split:
    kwargs:
      train_fraction: 0.7       
      random_seed: 42

tracker:
  wandb_project: 'eeg_online'
  wandb_mode:    'offline'
